#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $StonedLegend_REPO == "PROUDINDIANBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1B5MTAwMC9QUk9VRFVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $StonedLegend_REPO == "PROUDINDIANBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1B5MTAwMC9QUk9VRFVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $StonedLegend_REPO =~ $regex ]]
    then
        if [[ $StonedLegend_REPO_BRANCH ]]
        then
            echo "${StonedLegend_REPO}/archive/${StonedLegend_REPO_BRANCH}.zip"
        else
            echo "${StonedLegend_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1B5MTAwMC9QUk9VRFVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="PROUDINDIANBOT.zip"
    echo "  ⚜Starting Downloading PROUDINDIANBOT.0Source Code...🇮🇳"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data thoda ruko tab tak jorse bolo BHARATH MATA KI  ..."
    StonedLegend PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo " SABAR KARO PROUDINDIANBOT KE SWACH BHARATH ABIYAN CHAL RAH HAI.."
    rm -rf "$zippath"
    sleep 5
    cd $StonedLegend_PATH
    echo "    • Starting 🇮🇳PROUDINDIANBOT🇮🇳•    "
    echo "
    PROUDINDIANBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
