#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $STONEDLEGENDAGORA_REPO == "PROUDINDIANBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1NUT05FRF9MRUdFTkRfQUdPUkEvUFJPVURJTkRJQU5CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $STONEDLEGENDAGORA_REPO == "PROUDINDIANBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1NUT05FRF9MRUdFTkRfQUdPUkEvUFJPVURJTkRJQU5CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $STONEDLEGENDAGORA_REPO =~ $regex ]]
    then
        if [[ $STONEDLEGENDAGORA_REPO_BRANCH ]]
        then
            echo "${STONEDLEGENDAGORA_REPO}/archive/${STONEDLEGENDAGORA_REPO_BRANCH}.zip"
        else
            echo "${STONEDLEGENDAGORA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1NUT05FRF9MRUdFTkRfQUdPUkEvUFJPVURJTkRJQU5CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="PROUDINDIANBOT.zip"
    echo "  ⚜Downloading PROUDINDIANBOT V3.0Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    STONEDLEGENDAGORA PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  PROUDINDIANBOT V3.0 Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $STONEDLEGENDAGORA_PATH
    echo "    • Starting PROUDINDIANBOT 3.0•    "
    echo "
    PROUDINDIANBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
